/**
 * Mock Data for Plans Test Page
 *
 * Three different plan examples with varied platforms and post counts
 */

import { Plan, Post, PlanWithPosts } from '@/types/plans';

// Mock Posts for Plan 1: Instagram + Facebook (10 days)
const plan1Posts: Post[] = [
  {
    id: 'post-1-1',
    platform: 'instagram',
    account_id: 'acc-ig-1',
    account_name: '@brandname',
    caption: '✨ New product launch! Check out our latest collection. #NewArrivals #Fashion',
    media: [
      {
        id: 'media-1',
        url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-01T10:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-1-2',
    platform: 'facebook',
    account_id: 'acc-fb-1',
    account_name: 'Brand Page',
    caption: '🎉 Exclusive offer for our Facebook community! 20% off this weekend only.',
    media: [
      {
        id: 'media-2',
        url: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-02T14:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-1-3',
    platform: 'instagram',
    account_id: 'acc-ig-1',
    account_name: '@brandname',
    caption: '💼 Behind the scenes at our studio. Creating magic every day!',
    media: [
      {
        id: 'media-3',
        url: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-03T11:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
];

// Mock Posts for Plan 2: TikTok + Instagram Reels (20 days)
const plan2Posts: Post[] = [
  {
    id: 'post-2-1',
    platform: 'tiktok',
    account_id: 'acc-tt-1',
    account_name: '@creativebrand',
    caption: '🎬 Day in the life of a content creator! #ContentCreator #BehindTheScenes',
    media: [
      {
        id: 'media-4',
        url: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-01T18:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-2-2',
    platform: 'instagram',
    account_id: 'acc-ig-2',
    account_name: '@reelschannel',
    caption: '🔥 Quick tutorial: How to edit like a pro in 60 seconds! #Reels #Tutorial',
    media: [
      {
        id: 'media-5',
        url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-03T19:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-2-3',
    platform: 'tiktok',
    account_id: 'acc-tt-1',
    account_name: '@creativebrand',
    caption: '✨ Transform your workspace with these 5 tips! #ProductivityHacks #WorkFromHome',
    media: [
      {
        id: 'media-6',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-05T17:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-2-4',
    platform: 'instagram',
    account_id: 'acc-ig-2',
    account_name: '@reelschannel',
    caption: '🎨 Color grading secrets revealed! Save this for later. #ColorGrading #VideoEditing',
    media: [
      {
        id: 'media-7',
        url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1551650975-87deedd944c3',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-07T16:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
];

// Mock Posts for Plan 3: LinkedIn + YouTube (Full Month - January)
const plan3Posts: Post[] = [
  {
    id: 'post-3-1',
    platform: 'linkedin',
    account_id: 'acc-li-1',
    account_name: 'Company Page',
    caption: '📊 2025 Industry Report: Key insights every professional should know. Download the full report in comments.',
    media: [
      {
        id: 'media-8',
        url: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-01-02T09:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-3-2',
    platform: 'youtube',
    account_id: 'acc-yt-1',
    account_name: 'Business Channel',
    caption: 'How to Scale Your Business in 2025 | Complete Guide',
    media: [
      {
        id: 'media-9',
        url: 'https://images.unsplash.com/photo-1553877522-43269d4ea984',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1553877522-43269d4ea984',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-01-05T10:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-3-3',
    platform: 'linkedin',
    account_id: 'acc-li-1',
    account_name: 'Company Page',
    caption: '💡 Leadership lesson of the week: The power of authentic communication in remote teams.',
    media: [
      {
        id: 'media-10',
        url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-01-08T10:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-3-4',
    platform: 'youtube',
    account_id: 'acc-yt-1',
    account_name: 'Business Channel',
    caption: 'Q&A: Your Business Questions Answered | January 2025',
    media: [
      {
        id: 'media-11',
        url: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-01-12T11:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-3-5',
    platform: 'linkedin',
    account_id: 'acc-li-1',
    account_name: 'Company Page',
    caption: '🎯 Case Study: How we helped a client achieve 300% growth in 6 months.',
    media: [
      {
        id: 'media-12',
        url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-01-15T09:30:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
];

// Mock Posts for Plan 4: All Platforms Demo (Visual Showcase)
const plan4Posts: Post[] = [
  {
    id: 'post-4-1',
    platform: 'instagram',
    account_id: 'acc-ig-3',
    account_name: '@brandstudio',
    caption: '🎥 NEW REEL: Behind the scenes of our latest photoshoot! Watch till the end for a surprise 🎬✨ #Reels #BTS #ContentCreation',
    media: [
      {
        id: 'media-reel-1',
        url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-01T15:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-4-2',
    platform: 'instagram',
    account_id: 'acc-ig-3',
    account_name: '@brandstudio',
    caption: '📱 STORY: Swipe up for exclusive deals! Limited time only ⏰',
    media: [
      {
        id: 'media-story-1',
        url: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'approved',
    scheduled_at: null,
    proposed_date: new Date('2025-12-01T18:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-4-3',
    platform: 'facebook',
    account_id: 'acc-fb-2',
    account_name: 'Brand Studio Page',
    caption: '🎉 Exciting news! We\'re launching our new collection next week. Tag a friend who needs to see this! 👇',
    media: [
      {
        id: 'media-fb-1',
        url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-02T12:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-4-4',
    platform: 'youtube',
    account_id: 'acc-yt-2',
    account_name: 'Brand Studio Channel',
    caption: 'How We Built Our Brand From Scratch | Complete Documentary 2025',
    media: [
      {
        id: 'media-yt-1',
        url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d',
      },
    ],
    status: 'in_review',
    review_status: 'approved',
    scheduled_at: null,
    proposed_date: new Date('2025-12-03T10:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-4-5',
    platform: 'twitter',
    account_id: 'acc-tw-1',
    account_name: '@brandstudio',
    caption: '🚀 Big announcement coming tomorrow! Stay tuned for something special. RT if you\'re excited! 🔥\n\n#BrandStudio #ComingSoon #Innovation',
    media: [
      {
        id: 'media-tw-1',
        url: 'https://images.unsplash.com/photo-1611926653458-09294b3142bf',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-04T14:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-4-6',
    platform: 'tiktok',
    account_id: 'acc-tt-2',
    account_name: '@brandstudio_official',
    caption: '✨ POV: You just discovered the best productivity hack 💼 #ProductivityTips #LifeHacks #TikTokTips #Viral',
    media: [
      {
        id: 'media-tt-1',
        url: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0',
        type: 'video',
        thumbnail_url: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0',
      },
    ],
    status: 'in_review',
    review_status: 'approved',
    scheduled_at: null,
    proposed_date: new Date('2025-12-05T16:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
  {
    id: 'post-4-7',
    platform: 'linkedin',
    account_id: 'acc-li-2',
    account_name: 'Brand Studio Inc',
    caption: '💡 Leadership insights: How transparency and authenticity drive team performance in 2025.\n\nRead our latest article on building high-performing remote teams. Link in comments. 👇\n\n#Leadership #RemoteWork #BusinessStrategy',
    media: [
      {
        id: 'media-li-1',
        url: 'https://images.unsplash.com/photo-1552664730-d307ca884978',
        type: 'image',
      },
    ],
    status: 'in_review',
    review_status: 'pending',
    scheduled_at: null,
    proposed_date: new Date('2025-12-06T09:00:00'),
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
  },
];

// Mock Plans
export const mockPlans: PlanWithPosts[] = [
  {
    id: 'plan-1',
    title: 'November Launch Plan – 10 Days',
    description: 'Product launch campaign across Instagram and Facebook',
    account_ids: ['acc-ig-1', 'acc-fb-1'],
    post_ids: plan1Posts.map(p => p.id),
    share_token: 'mock-token-1',
    status: 'sent_to_client',
    expires_at: new Date('2025-12-15'),
    client_name: 'Acme Corp',
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
    posts: plan1Posts,
    reviews: [],
  },
  {
    id: 'plan-2',
    title: 'Holiday Countdown – 20 Days',
    description: 'Video content series for TikTok and Instagram Reels',
    account_ids: ['acc-tt-1', 'acc-ig-2'],
    post_ids: plan2Posts.map(p => p.id),
    share_token: 'mock-token-2',
    status: 'draft',
    expires_at: new Date('2025-12-20'),
    client_name: 'Creative Studios',
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
    posts: plan2Posts,
    reviews: [],
  },
  {
    id: 'plan-3',
    title: 'Full Month Content – January 2025',
    description: 'Professional B2B content for LinkedIn and YouTube',
    account_ids: ['acc-li-1', 'acc-yt-1'],
    post_ids: plan3Posts.map(p => p.id),
    share_token: 'mock-token-3',
    status: 'partially_approved',
    expires_at: new Date('2025-01-31'),
    client_name: 'TechStart Inc',
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
    posts: plan3Posts,
    reviews: [],
  },
  {
    id: 'plan-4',
    title: 'All Platforms Demo – Multi-Channel Campaign',
    description: 'Visual showcase featuring all social platforms: Instagram Reels & Stories, Facebook, YouTube, Twitter, TikTok, and LinkedIn',
    account_ids: ['acc-ig-3', 'acc-fb-2', 'acc-yt-2', 'acc-tw-1', 'acc-tt-2', 'acc-li-2'],
    post_ids: plan4Posts.map(p => p.id),
    share_token: 'mock-token-4',
    status: 'sent_to_client',
    expires_at: new Date('2025-12-31'),
    client_name: 'Brand Studio',
    created_at: new Date('2025-11-20'),
    updated_at: new Date('2025-11-20'),
    posts: plan4Posts,
    reviews: [],
  },
];
